# Generated by Django 4.1.5 on 2023-02-17 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_created_alter_article_publish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="publish",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
