# Generated by Django 4.1.5 on 2023-03-10 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0003_alter_article_created_alter_article_publish_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="likes",
            field=models.ManyToManyField(
                related_name="articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
